@startuml
title State Diagram: Процесс работы администратора

  [*] --> Проверка_заявок_создания_организаций
  state Проверка_заявок_создания_организаций {
    [*] --> Создание_аккаунта_организации : Заявка одобрена
    [*] --> Отклонение_заявки : Заявка отклонена
  }
  
  state Модерация_заданий {
    [*] --> Анализ_задания
    Анализ_задания --> Блокировка_задания : Нарушения найдены
    Блокировка_задания --> Уведомление_о_блокировке_задания
    Анализ_задания --> Разблокировка_задания : Задание заблокировано и нарушений не найдено
    Разблокировка_задания --> Уведомление_о_разблокировке_задания
  }
  
  state Проверка_пользователей {
    [*] --> Анализ_профиля
    Анализ_профиля --> Блокировка_пользователя : Нарушения обнаружены
    Блокировка_пользователя --> Уведомление_пользователя
    Анализ_профиля --> Разблокировка_пользователя : Пользователь заблокирован
    Разблокировка_пользователя --> Уведомление_о_разблокировке
  }
  
  Проверка_заявок_создания_организаций --> Модерация_заданий
  Модерация_заданий --> Проверка_пользователей
  Проверка_пользователей --> Создание_администраторов : При необходимости


Создание_администраторов --> [*]
@enduml