server:
  port: "8080"
  host: "localhost"
db:
  port: "5432"
  host: "dapomogu_postgres"
  username: "postgres"
  dbname: "dapomogu_chat_db"
  ssl_mode: "disable"
  password: "dapomogu_password"
kafka:
  port: "9092"
  host: "kafka"
  users_topic: "users_topic"
  groups_topic: "groups_topic"
  group_id: "users_topic"
address:
  "user-service:50501"
notification_address:
  "notification_service:50501"
jwt_secret: "verysecret"
