server:
  port: "8080"
  host: "localhost"
db:
  port: "5432"
  host: "postgres-service"
  username: "postgres"
  dbname: "dapomogu_chat_db"
  ssl_mode: "disable"
  password: "dapomogu_password"
address:
  "user-service:50501"
notification_address:
  "notification_service:50501"
jwt_secret: "verysecret"
