// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: task.proto

package task

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskService_GetTasksByOrganizationId_FullMethodName       = "/functions.TaskService/GetTasksByOrganizationId"
	TaskService_GetCountTasksCompletedByUserId_FullMethodName = "/functions.TaskService/GetCountTasksCompletedByUserId"
	TaskService_GetCountTasksCompleted_FullMethodName         = "/functions.TaskService/GetCountTasksCompleted"
	TaskService_GetCountActiveTasks_FullMethodName            = "/functions.TaskService/GetCountActiveTasks"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceClient interface {
	GetTasksByOrganizationId(ctx context.Context, in *TaskOrganizationRequest, opts ...grpc.CallOption) (*TasksViewInProfileOrganization, error)
	GetCountTasksCompletedByUserId(ctx context.Context, in *TaskUserRequest, opts ...grpc.CallOption) (*TasksCompleteCountResponse, error)
	GetCountTasksCompleted(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TasksCompleteCountResponse, error)
	GetCountActiveTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TasksCountResponse, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) GetTasksByOrganizationId(ctx context.Context, in *TaskOrganizationRequest, opts ...grpc.CallOption) (*TasksViewInProfileOrganization, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TasksViewInProfileOrganization)
	err := c.cc.Invoke(ctx, TaskService_GetTasksByOrganizationId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetCountTasksCompletedByUserId(ctx context.Context, in *TaskUserRequest, opts ...grpc.CallOption) (*TasksCompleteCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TasksCompleteCountResponse)
	err := c.cc.Invoke(ctx, TaskService_GetCountTasksCompletedByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetCountTasksCompleted(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TasksCompleteCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TasksCompleteCountResponse)
	err := c.cc.Invoke(ctx, TaskService_GetCountTasksCompleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetCountActiveTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TasksCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TasksCountResponse)
	err := c.cc.Invoke(ctx, TaskService_GetCountActiveTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility.
type TaskServiceServer interface {
	GetTasksByOrganizationId(context.Context, *TaskOrganizationRequest) (*TasksViewInProfileOrganization, error)
	GetCountTasksCompletedByUserId(context.Context, *TaskUserRequest) (*TasksCompleteCountResponse, error)
	GetCountTasksCompleted(context.Context, *Empty) (*TasksCompleteCountResponse, error)
	GetCountActiveTasks(context.Context, *Empty) (*TasksCountResponse, error)
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) GetTasksByOrganizationId(context.Context, *TaskOrganizationRequest) (*TasksViewInProfileOrganization, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTasksByOrganizationId not implemented")
}
func (UnimplementedTaskServiceServer) GetCountTasksCompletedByUserId(context.Context, *TaskUserRequest) (*TasksCompleteCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountTasksCompletedByUserId not implemented")
}
func (UnimplementedTaskServiceServer) GetCountTasksCompleted(context.Context, *Empty) (*TasksCompleteCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountTasksCompleted not implemented")
}
func (UnimplementedTaskServiceServer) GetCountActiveTasks(context.Context, *Empty) (*TasksCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountActiveTasks not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}
func (UnimplementedTaskServiceServer) testEmbeddedByValue()                     {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	// If the following call pancis, it indicates UnimplementedTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_GetTasksByOrganizationId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTasksByOrganizationId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTasksByOrganizationId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTasksByOrganizationId(ctx, req.(*TaskOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetCountTasksCompletedByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetCountTasksCompletedByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetCountTasksCompletedByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetCountTasksCompletedByUserId(ctx, req.(*TaskUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetCountTasksCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetCountTasksCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetCountTasksCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetCountTasksCompleted(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetCountActiveTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetCountActiveTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetCountActiveTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetCountActiveTasks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "functions.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTasksByOrganizationId",
			Handler:    _TaskService_GetTasksByOrganizationId_Handler,
		},
		{
			MethodName: "GetCountTasksCompletedByUserId",
			Handler:    _TaskService_GetCountTasksCompletedByUserId_Handler,
		},
		{
			MethodName: "GetCountTasksCompleted",
			Handler:    _TaskService_GetCountTasksCompleted_Handler,
		},
		{
			MethodName: "GetCountActiveTasks",
			Handler:    _TaskService_GetCountActiveTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task.proto",
}
