CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(150) UNIQUE NOT NULL,
    phone VARCHAR(18) NOT NULL,
    surname VARCHAR(255) NULL,
    name VARCHAR(255) NOT NULL,
    patronymic VARCHAR(255) NULL,
    date_of_birthday DATE NULL,
    address VARCHAR(255) NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
