apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE DATABASE dapomogu_user_db;
    CREATE DATABASE dapomogu_task_db;
    CREATE DATABASE dapomogu_notification_db;
    CREATE DATABASE dapomogu_chat_db;
