apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: den990/task_service:latest
          ports:
            - containerPort: 8085
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:dapomogu_password@postgres-service:5439/dapomogu_task_db"
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: ClusterIP
