apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: den990/task_service:1.0.119
          ports:
            - containerPort: 8080
            - containerPort: 50501  # Добавляем gRPC-порт
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:dapomogu_password@postgres-service:5432/dapomogu_task_db"
            - name: USER_SERVICE_GRPC
              value: "user-service:50501"
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30081
    - name: grpc
      protocol: TCP
      port: 50501
      targetPort: 50501
  type: NodePort
