apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: den990/user_service:1.0.95
          ports:
            - name: http
              containerPort: 8080  # HTTP API
            - name: https
              containerPort: 443
            - name: grpc
              containerPort: 50501 # gRPC API
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:dapomogu_password@postgres-service:5432/dapomogu_user_db"
            - name: TASK_SERVICE_GRPC
              value: "task-service:50501"
            - name: NOTIFICATION_SERVICE_GRPC
              value: "notification-service:50501"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: grpc
      protocol: TCP
      port: 50501
      targetPort: 50501
  type: NodePort
