apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: den990/user_service:latest
          ports:
            - containerPort: 8086
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:dapomogu_password@postgres-service:5439/dapomogu_user_db"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8086
  type: ClusterIP
