@startuml
|Водитель|
|Пользователь|
start
|Пользователь|
:Заказ такси;
if (Есть долг?) then (нет)
    :Выбор начальной точки;
    :Выбор конечной точки;
    :Выбор способа оплаты;
    :Заказ такси;
    |Система|
    :Поиск водителя;
    |Водитель|
    :Выход на линию;
    |Система|
    if (Пройден фотоконтроль?) then (да)
        |Водитель|
        :Вышел на линию;
        |Система|
        if (Водитель принял заказ?) then (да)
            -> Назначение водителя;
        else (нет)
            :Исключение водителя из списка доступных;
            :Поиск другого водителя;
            if (Найден другой водитель?) then (да)
                -> Назначение водителя;
            else (нет)
                :Вывод сообщения: "Нет доступных водителей";    
                stop
            endif
        endif   
    else (нет)
        :Вывод сообщения о необходимости пройти фотоконтроль;
        stop
    endif
else (да)
    :Вывод сообщения о погашении долга, запрет на заказ такси;
    stop
endif
|Система|
:Назначение водителя;
:Отправка сообщения пользователю о том что водитель найден;
|Водитель|
:Прибыл на место отправки;
|Система|
:Изменения статуса поездки;
|Пользователь|
:Сел в машину;
|Водитель|
:Начал поездку;
|Система|
:Изменения статуса поездки;
|Водитель|
:Приехал на конечную точку;
:Закончил поездку;
|Система|
:Изменения статуса поездки;
:Списание денег у пользователя;
if (Баланс на карте больше суммы поездки?) then (да)
    ->Пополнение баланса водителя выполняющего поездку;
else (нет)
    :Выставления долга пользователю;
    ->Пополнение баланса водителя выполняющего поездку;
endif

:Пополнение баланса водителя выполняющего поездку;
|Водитель|
:Поставил оценку пользователю;
|Пользователь|
:Поставил оценку водителю;
end
@enduml
