@startuml
skinparam style classic

title Use Case.Управление заданиями для Организации

:Организация:

Организация -- (Создать задание)
(Создать задание) <-up- (Редактировать задание) : <<extend>>
(Создать задание) <-up- (Удалить задание) : <<extend>>
(Создать задание) <-- (Оставить комментарий к заданию) : <<include>>
(Создать задание) <-- (Подтвердить участие) : <<include>>
Организация -- (Поиск заданий)
Организация -- (Оставить комментарий к заданию)
Организация -- (Подтвердить участие)
@enduml