@startuml
skinparam style classic

title Use Case.Управление заданиями для роли Волонтёр

:Волонтёр:
:Координатор:

Волонтёр -- (Откликнуться на задание)
Волонтёр -- (Оставить комментарий к заданию)
Волонтёр -- (Отправить фотоотчёт)
(Подтвердить участие) <-- (Оставить комментарий к заданию) : <<include>>
(Подтвердить участие) <-- (Отправить фотоотчёт) : <<include>>

Координатор -- (Подтвердить выполнение)
Координатор -- (Подтвердить участие)
Координатор -- (Отменить участие волонтёра)
Координатор -- (Оставить комментарий к заданию)

Волонтёр -- (Поиск заданий)

(Подтвердить участие) <-- (Подтвердить выполнение) : <<include>>
(Подтвердить участие) <-- (Отменить участие волонтёра) : <<include>>
(Откликнуться на задание) <-- (Подтвердить участие) : <<include>>
@enduml