@startuml
skinparam style classic

title Use Case.Администрирование системы

:Администратор:

Администратор -- (Создать аккаунт администратора)
Администратор -- (Модерировать задание)
Администратор -- (Заблокировать пользователя)
(Заблокировать пользователя) <-- (Разблокировать пользователя) : <<include>>

@enduml