@startuml

skinparam style classic

title Use Case.Сценарий организации

:Организация: 

Организация --> (Создать задачу)
(Создать задачу) --> (Отменить задачу)
(Создать задачу) --> (Редактировать задачу)
(Создать задачу) --> (Выбрать Координатора из списка Волонтёров)

Организация --> (Просмотр профиля)
(Просмотр профиля) --> (Редактировать профиль)

@enduml