@startuml

skinparam style classic

title Use Case.Сценарий зрителя

:Зритель: 

Зритель --> (Регистрация волонтёра)
(Регистрация волонтёра) --> Волонтёр

Зритель --> (Регистрация организации)
(Регистрация организации) --> Организация

Зритель --> (Просмотр статиститки)
Зритель --> (Просмотр списка заданий)
(Просмотр списка заданий) --> (Посмотреть описание задания)

@enduml