@startuml

skinparam style classic

title Use Case.Сценарий волонтёра

:Волонтёр: 
:Координатор:
:Организация:

Волонтёр --> (Выдача роли Координатор)
(Выдача роли Координатор) --> Координатор
Организация --> (Выдача роли Координатор)

Волонтёр --> (Просмотр статиститки)
Волонтёр --> (Просмотр списка задач)
(Просмотр списка задач) --> (Просмотреть задачу)
Волонтёр --> (Просмотр профиля)
(Просмотр профиля) --> (Редактировать профиль)

Волонтёр --> (Откликнуться на задачу)
(Откликнуться на задачу) --> (Подтвердить участие волонтера)
(Откликнуться на задачу) --> (Отказаться от задачи)
Координатор --> (Подтвердить участие волонтера)

(Подтвердить участие волонтера) --> (Отказаться от задачи)
(Подтвердить участие волонтера) --> (Посмотреть детали)
(Подтвердить участие волонтера) --> (Завершение задачи)

@enduml