@startuml

skinparam style classic

title Use Case.Сценарий координатора

:Координатор:

Координатор --> (Подтвердить участие волонтера)
Координатор --> (Проверка выполенения)
(Проверка выполенения) --> (Подтвердить выполнение задания)
(Проверка выполенения) --> (Вернуть задание на доработку/в лист)
(Подтвердить выполнение задания) --> (Поставить оценку)

@enduml