@startuml

skinparam style classic

title Use Case.Сценарий администратора

:Администратор: 

Администратор --> (Модерация контента)
Администратор --> (Блокировка пользователя)
(Блокировка пользователя) --> (Восстановление доступа)

@enduml