@startuml

skinparam style classic

title Use Case.Сценарий координатора

:Волонтёр: 
:Координатор: 
:Организация:

Волонтёр --> (Выдача роли Координатор)
(Выдача роли Координатор) --> Координатор
Организация --> (Выдача роли Координатор)

Координатор --> (Подтвердить участие волонтера)
Координатор --> (Проверка выполенения)
(Проверка выполенения) --> (Подтвердить выполнение задачи)
(Проверка выполенения) --> (Вернуть задачу на доработку/в лист)
(Подтвердить выполнение задачи) --> (Поставить оценку)

@enduml