@startuml

skinparam style classic

title Use Case.Сценарий организации

:Организация:

Организация --> (Создать задание)
(Создать задание) --> (Отменить задание)
(Создать задание) --> (Редактировать задание)
(Создать задание) --> (Выбрать Координатора из списка Волонтёров)
(Выбрать Координатора из списка Волонтёров) --> (Изменить Координатора)

Организация --> (Просмотр профиля)
(Просмотр профиля) --> (Редактировать профиль)

@enduml
