@startuml

skinparam style classic

title Use Case.Сценарий волонтёра

:Волонтёр:

Волонтёр --> (Просмотр статиститки)
Волонтёр --> (Просмотр списка заданий)
(Просмотр списка заданий) --> (Посмотреть описание задания)
Волонтёр --> (Просмотр профиля)
(Просмотр профиля) --> (Редактировать профиль)

Волонтёр --> (Откликнуться на задание)
(Откликнуться на задание) --> (Координатор подтвердил участие)

(Координатор подтвердил участие) --> (Отказаться от задания)
(Координатор подтвердил участие) --> (Посмотреть детали)
(Координатор подтвердил участие) --> (Завершить задание)

@enduml
