@startuml
skinparam style classic

title Use Case.Работа с профилем

:Волонтёр:
:Организация:
:Администратор:

Гость -- (Просмотр профиля организации)
Волонтёр -- (Просмотр профиля организации)
Организация -- (Просмотр профиля организации)
Администратор -- (Просмотр профиля организации)

Волонтёр -- (Просмотр профиля волонтера)
Организация -- (Просмотр профиля волонтера)
Администратор -- (Просмотр профиля волонтера)

Волонтёр -- (Просмотр актиных заданий)

Администратор -- (Рассмотреть заявку на регистрацию)
(Создать заявку на регистрацию организации) <-- (Рассмотреть заявку на регистрацию) : <<include>>

Организация -- (Создать заявку на редактирование организации)
Администратор -- (Рассмотреть заявку на редактирование организации)
(Создать заявку на редактирование организации) <-- (Рассмотреть заявку на редактирование организации) : <<include>>

Волонтёр -- (Отправить заявку на прикрепление к организации)
(Отправить заявку на прикрепление к организации) <-- (Рассмотреть заявку на прикрепление) : <<include>>
Организация -- (Рассмотреть заявку на прикрепление)
Волонтёр -- (Изменить личные данные)
Волонтёр -- (Просмотр статистики)
Организация -- (Просмотр статистики)

Гость -- (Регистрация волонтёра)
Гость -- (Авторизация)
Гость -- (Создать заявку на регистрацию организации)
(Регистрация волонтёра) -- Волонтёр


(Авторизация) -- Волонтёр
(Авторизация) -- Администратор
(Авторизация) -- Организация
@enduml