@startuml
skinparam style classic

title Use Case.Работа с профилем

:Волонтёр:
:Организация:
:Администратор:

Организация --> (Создать заявку на редактирование огранизации)
(Создать заявку на редактирование огранизации) <-- (Рассмотреть заявку на регистрацию/редактировнаие) : <<include>>
Администратор --> (Рассмотреть заявку на регистрацию/редактировнаие)

Волонтёр --> (Отправить заявку на прикрепление к организации)
(Отправить заявку на прикрепление к организации) <-- (Рассмотреть заявку на прикрепление) : <<include>>
Организация --> (Рассмотреть заявку на прикрепление)
Волонтёр --> (Изменить личные данные)
Волонтёр --> (Просмотр статистики)
Организация --> (Просмотр статистики)

Гость --> (Регистрация волонтёра)
Гость --> (Авторизация)
Гость --> (Создать заявку на регистрацию аккаунта)
(Регистрация волонтёра) --> Волонтёр

(Создать заявку на регистрацию аккаунта) <-- (Рассмотреть заявку на регистрацию/редактировнаие) : <<include>>

(Авторизация) --> Волонтёр
(Авторизация) --> Администратор
(Авторизация) --> Организация
@enduml