@startuml

skinparam style classic

title Use Case.Сценарий администратора

:Администратор:

Администратор --> (Войти в систему)
Администратор --> (Выйти из системы)
Администратор --> (Просмотреть профили пользовтелей)
Администратор --> (Просмотреть задачи)
(Просмотреть задачи) --> (Просмотреть задачу)
(Просмотреть профили пользовтелей) --> (Просмотреть профиль)
(Просмотреть профиль) --> (Редактировать профиль)
(Просмотреть задачу) --> (Удалить задачу)
(Просмотреть профиль) --> (Заблокриовать профиль)
(Просмотреть задачу) --> (Редактировать задачу)
Администратор --> (Просмотр статистики)
Администратор --> (Блокировка пользователя)
(Блокировка пользователя) --> (Восстановление доступа)

@enduml


