@startuml
skinparam style classic

title Use Case.Сценарий волонтёра

:Волонтёр:
actor "Координатор" as Coordinator

Волонтёр --> (Просмотр статиститки)
Волонтёр --> (Войти в систему)
Волонтёр --> (Выйти из системы)
Волонтёр --> (Зарегестрироваться)
Волонтёр --> (Просмотр списка заданий)
(Просмотр списка заданий) --> (Посмотреть задание)
(Просмотр списка заданий) --> (Просмотр своих заданий)
(Посмотреть задание) --> (Если волонтер является координатором)
(Если волонтер является координатором) --> Coordinator
Волонтёр --> (Просмотр профиля)
(Просмотр профиля) --> (Редактировать профиль)

(Просмотр списка заданий) --> (Откликнуться на задание)

(Посмотреть задание) --> (Отказаться от задания)
(Посмотреть задание) --> (Посмотреть детали)
(Посмотреть задание) --> (Завершить задание)

Coordinator --> (Просмотр списка волонтёров)
(Просмотр списка волонтёров) --> (Подтвердить участие волонтера)
Coordinator --> (Проверка выполнения)
(Проверка выполнения) --> (Подтвердить выполнение задания)
(Проверка выполнения) --> (Вернуть задание на доработку/в лист)
(Просмотр списка волонтёров) --> (Поставить оценку)
(Просмотр списка волонтёров) --> (Связаться с волонтёром)
(Подтвердить выполнение задания) --> (Оценить качество выполнения задания)
@enduml

