@startuml
skinparam style classic

' --- Сценарий Организации ---
title Use Case. Сценарий Организации

actor "Организация" as Organization

Organization --> (Залогиниться в систему)
Organization --> (Подать заявку на регистрацию)
Organization --> (Создать задание)
(Создать задание) --> (Отменить задание)
(Создать задание) --> (Редактировать задание)
(Создать задание) --> (Выбрать Координатора из списка Волонтёров)
(Выбрать Координатора из списка Волонтёров) --> (Изменить Координатора)
Organization --> (Просмотр профиля)
(Просмотр профиля) --> (Редактировать профиль)
(Создать задание) --> (Добавить описание к заданию)
(Создать задание) --> (Указать сроки выполнения задания)
Organization --> (Просмотр заданий)
(Просмотр заданий) --> (Просмотр задания)
(Просмотр задания) --> (Добавить описание к заданию)
(Просмотр задания) --> (Указать сроки выполнения задания)
(Просмотр задания) --> (Отменить задание)
(Просмотр задания) --> (Редактировать задание)
(Просмотр задания) --> (Выбрать Координатора из списка Волонтёров)
Organization --> (Просмотр статистики)
Organization --> (Выйти из системы)

@enduml

