@startuml
title Процесс выполнения задания

start
:Волонтер выполняет поиск заданий;
if (Задание найдено?) then (Да)
  :Отклик на задание;
  if (Тип задания - Закрытый?) then (Да)
    if (Прикреплен к организации?) then (Да)
      :Подача заявки;
    else (Нет)
      :Уведомление "Требуется прикрепление";
      stop
    endif
  else (Нет)
      :Подача заявки;
  endif
  :Подтверждение участия;
  :Координатор проверяет заявку;
  if (Утверждено?) then (Да)
    :Выполнение задания;
    :Отправка фотоотчета;
    :Координатор подтверждает выполнение;
    :Начисление баллов;
    stop
  else (Нет)
    :Уведомление об отказе;
    stop
  endif
else (Нет)
  :Завершение процесса;
  stop
endif
@enduml