@startuml
title Activity Diagram: Организация (Создание задания)

start
:Авторизация;
:Переход в раздел "Создать задание";
:Ввод данных;
:Назначение координатора;
:Публикация задания;
:Уведомление волонтеров (email);
:Редактирование задания (при необходимости);
:Удаление задания (при необходимости);
stop
@enduml