@startuml
title Activity Diagram: Администратор

start
:Авторизация;
:Проверка заявок на регистрацию организаций;
if (Заявка одобрена?) then (Да)
  :Создание аккаунта организации;
else (Нет)
  :Отклонение заявки;
endif

:Модерация заданий;
if (Нарушения найдены?) then (Да)
  :Блокировка задания;
  :Уведомление организации;
else (Нет)
endif

:Проверка пользователей;
if (Обнаружены нарушения?) then (Да)
  fork
    :Блокировка пользователя;
  fork again
    :Уведомление о причине блокировки;
  end fork
else (Нет)
  if (Заблокирован?) then (Да)
  fork
    :Разблокировка пользователя;
  fork again
    :Уведомление о разблокировке;
  end fork
  else (Нет)
  endif
endif

:Создание аккаунтов администраторов (при необходимости);
stop
@enduml