@startuml
title Sequence Diagram: Создание задания организацией

actor Организация
participant "Система" as System
participant Координатор
participant "Email Сервис" as Email
database БазаДанных

Организация -> System: Запрос на создание задания
System --> Организация: Открытие формы ввода данных

Организация -> System: Ввод данных
System -> БазаДанных: Сохранение черновика задания

Организация -> System: Назначить координатора (выбор из списка)
System -> Координатор: Уведомление о назначении
System -> БазаДанных: Сохранение изменений(Назначение координатора)

Организация -> System: Опубликовать
System -> Email: Запрос на рассылку уведомлений
Email -> Волонтеры: Рассылка о новом задании

loop Редактирование (опционально)
  Организация -> System: Запрос на редактирование
  System --> Организация: Открытие формы редактирования
  Организация -> System: Ввод изменений
  System -> БазаДанных: Обновление данных
end

opt Удаление (опционально)
  Организация -> System: Запрос на удаление
  System -> БазаДанных: Удаление задания
  System -> Координатор: Уведомление об отмене задания
  System -> Email: Запрос на рассылку отмены задания
  Email -> Волонтеры: Рассылка об отмене задания
end
@enduml