@startuml
title Sequence Diagram: Модерация контента администратором

participant Администратор
participant Система
participant Организация
participant Волонтер

Администратор -> Система: Запрос на модерацию новых заданий
Система --> Администратор: Список не проверенных заданий

Администратор -> Система: Просмотр деталей задания
Система --> Администратор: Отображение полных данных

alt Нарушения найдены
  Администратор -> Система: Блокировка задания
  Система -> Организация: Уведомление о блокировке задания
  Система -> Волонтер: Уведомление об отмене задания
else Нарушения исправлены
  Администратор -> Система: Разблокировать задание
  Система -> Организация: Уведомление о разблокировке задания
  Система -> Волонтер: Уведомление о разблокировке задания
end

Администратор -> Система: Проверка профиля организации
Система --> Администратор: История активности
alt Нарушения найдены
  Администратор -> Система: Блокировка аккаунта
  Система -> Организация: Уведомление о блокировке
else Нарушения исправлены
  Администратор -> Система: Разблокировать аккаунт
  Система -> Организация: Уведомление о разблокировке
  
end

Администратор -> Система: Проверка профиля волонтера
Система --> Администратор: История активности
alt Нарушения найдены
  Администратор -> Система: Блокировка аккаунта
  Система -> Волонтер: Уведомление о блокировке
else Нарушения исправлены
  Администратор -> Система: Разблокировать аккаунт
  Система -> Волонтер: Уведомление о разблокировке
  
end
@enduml