apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-cert-challenge@kubernetescrd
spec:
  rules:
    - host: dapomogu.tw1.su
      http:
        paths:
          - path: "/.well-known/acme-challenge/"
            pathType: Prefix
            backend:
              service:
                name: cm-acme-http-solver-cpw6v
                port:
                  number: 80
