apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod  # Указываем наш ClusterIssuer
spec:
  tls:
    - hosts:
        - dapomogu.tw1.su  # Ваш домен
      secretName: dapomogu-tls  # Это имя секрета, где будет храниться сертификат
  rules:
    - host: dapomogu.tw1.su
      http:
        paths:
          # Сначала обрабатываем запросы для acme challenge
          - path: /.well-known/acme-challenge/
            pathType: Exact
            backend:
              service:
                name: cm-acme-http-solver-wh5gj
                port:
                  number: 80
          # Затем обрабатываем все остальные запросы
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
