version: '3.8'

services:
  db_task_service:
    container_name: db_task_service
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dapomogu_password}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped

  backend_app_task_service:
    container_name: backend_app_task_service
    build:
      context: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dapomogu_password}
      DB_NAME: ${DB_NAME:-dapomogu_task_db}
    depends_on:
      - db_task_service
    ports:
      - "8081:8080"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: